spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meetroom
    username: meetroom
    password: meetroom
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
      hibernate:
        type: trace
